apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}
  labels:
    type: local
    app: {{ .Values.name }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{ .Values.hostPath }}/{{ .Values.name }}"
  persistentVolumeReclaimPolicy: Retain 
