apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Microk8s controller-manager, scheduler and kube-proxy metrics in Prometheus
name: microk8s-kube-metrics
type: application
version: 0.0.1
home: https://github.com/georgedriver/helm-charts
sources:
  - https://github.com/georgedriver/helm-charts
keywords:
  - microk8s
  - prometheus
  - metrics
maintainers:
  - name: George
