# Default values for godaddy-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# domain -- The domain we're using for godaddy-webhook
domain: "test.com"

# email -- A validated email address for cert-manager
email: "test@test.com"

# godaddy_api_key -- GODADDY_API_KEY to handle the Godaddy DNS records
godaddy_api_key: ""
# godaddy_api_secret -- GODADDY_API_SECRET to handle the Godaddy DNS records
godaddy_api_secret: ""
