---

apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    # Change to your letsencrypt email
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - dns01:
        webhook:
          config:
            apiKeySecretRef:
              name: godaddy-secret
              key: key
              secret: secret
            production: true
            ttl: 600
          groupName: cert-manager.io
          solverName: godaddy
