---

apiVersion: v1
kind: Secret
metadata:
  name: godaddy-secret
  namespace: cert-manager
data:
  key: {{ printf "%s" .Values.godaddy_api_key | b64enc }}
  secret: {{ printf "%s" .Values.godaddy_api_secret | b64enc }}
