---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: test-cert-tls-secret
  namespace: cert-manager
spec:
  secretName: test-cert-tls-secret
  commonName: test-cert.{{ .Values.domain }}
  dnsNames:
  - test-cert.{{ .Values.domain }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
